name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request_target:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven and Generate JaCoCo Report
      run: mvn -B package -DskipTests jacoco:report
    - name: Extract Coverage Percentage
      id: coverage
      run: |
        COVERAGE=$(sed -n 's/.*<span class="ctr[^>]*>\([^<]*\)<\/span>%.*$/\1/p' target/site/jacoco/index.html)
        echo "::set-output name=coverage::$COVERAGE"

  comment:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Comment on PR with Coverage
      run: |
        echo "Code coverage: ${{ needs.build.outputs.coverage }}%"
        TOKEN=${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER=$(jq -r ".pull_request.number" "$GITHUB_EVENT_PATH")
        URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
        PAYLOAD="{\"body\":\"Code coverage: ${{ needs.build.outputs.coverage }}%\"}"
        curl -sS -H "Authorization: Bearer $TOKEN" -X POST -d "$PAYLOAD" "$URL"


   
