
name: PR Decoration with JaCoCo Coverage

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pr-decoration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and Test with JaCoCo
        run: |
          ./mvnw clean verify
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Extract Coverage Percentage
        id: extract-coverage
        run: |
          COVERAGE=$(./mvnw jacoco:report -Pjacoco-report | grep "Total" | awk '{print $3}' | sed 's/%//')
          echo "Coverage: $COVERAGE%"
          echo "::set-output name=coverage::$COVERAGE"

      - name: Post PR Comment
        if: always()
        uses: actions/github-script@v4
        with:
          script: |
            const coverage = "${{ steps.extract-coverage.outputs.coverage }}";
            const prNumber = context.payload.pull_request.number;
            const repoToken = process.env.GITHUB_TOKEN;

            const octokit = new github.getOctokit(repoToken);

            octokit.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `Code coverage: ${coverage}%`,
            });
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

   
