
name: PR Decoration with JaCoCo Coverage

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pr-decoration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Ensure execute permissions for mvnw
        run: chmod +x mvnw

      - name: Build and Test with JaCoCo
        run: |
          ./mvnw clean verify
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: ${{ github.workspace }}/target/site/jacoco/jacoco.xml

      - name: Extract Coverage Percentage
        id: extract-coverage
        run: |
          COVERAGE=$(sed -n 's/.*<span class="ctr[^>]*>\([^<]*\)<\/span>%.*$/\1/p' target/site/jacoco/index.html)
          echo "Coverage: $COVERAGE%"
          echo "::set-output name=coverage::$COVERAGE"
   
