name: Java CI with Maven

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B clean verify

    - name: Generate Code Coverage Report
      run: mvn -B jacoco:report

    - name: Extract Code Coverage Information
      id: coverage
      run: |
        COVERAGE=$(sed -n 's/.*Overall coverage rate \([^%]*\)\%.*/\1/p' target/site/jacoco/index.html)
        echo "::set-output name=coverage::$COVERAGE"

    - name: Get owner name
      id: get_owner
      run: echo "OWNER=$(jq -r '.repository.owner.login' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV

    - name: Comment Code Coverage on Pull Request
      if: github.event_name == 'pull_request'
      run: |
        coverage="${{ steps.coverage.outputs.coverage }}"
        owner="${{ env.OWNER }}"
        repo="${{ github.repository }}"
        prNumber="${{ github.event.pull_request.number }}"
        if [ -n "$coverage" ] && [ -n "$owner" ] && [ -n "$repo" ] && [ -n "$prNumber" ]; then
          comment="Owner: $owner\nCode Coverage: $coverage%"
          response=$(curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{\"body\":\"$comment\"}" "https://api.github.com/repos/$repo/issues/$prNumber/comments")
          if [ $? -eq 0 ]; then
            echo "Comment posted successfully."
          else
            echo "Failed to post comment: $response"
          fi
        else
          echo "One or more necessary information is missing. Unable to create comment."
        fi
