name: Java CI with Maven

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B clean verify

    - name: Generate Code Coverage Report
      run: mvn -B jacoco:report

    - name: Extract Code Coverage Information
      id: coverage
      run: |
        COVERAGE=$(sed -n 's/.*Overall coverage rate \([^%]*\)\%.*/\1/p' target/site/jacoco/index.html)
        echo "::set-output name=coverage::$COVERAGE"

    - name: Comment Code Coverage and Owner Name on Pull Request
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          async function run() {
            try {
              const owner = context.payload.repository?.owner?.login;
              console.log('Owner:', owner);

              const coverage = '${{ steps.coverage.outputs.coverage }}';
              console.log('Coverage:', coverage);

              const repo = context.payload.repository?.name;
              console.log('Repository:', repo);

              const prNumber = context.payload.pull_request?.number;
              console.log('Pull Request Number:', prNumber);

              if (owner && repo && prNumber && coverage) {
                const comment = `Owner: ${owner}\nCode Coverage: ${coverage}%`;
                console.log('Attempting to post comment...');
                await github.issues.createComment({
                  owner,
                  repo,
                  issue_number: prNumber,
                  body: comment
                });
                console.log('Comment posted successfully.');
              } else {
                console.error('One or more necessary information is missing. Unable to create comment.');
              }
            } catch (error) {
              console.error('Error occurred while commenting on pull request:', error.message);
            }
          }

          run();
