name: Java CI with Maven

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Extract Owner Name
      run: owner=$(jq -r '.repository.owner.login' $GITHUB_EVENT_PATH)

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B clean verify

    - name: Generate Code Coverage Report
      run: mvn -B jacoco:report

    - name: Extract Code Coverage Information
      id: coverage
      run: |
        COVERAGE=$(sed -n 's/.*Overall coverage rate \([^%]*\)\%.*/\1/p' target/site/jacoco/index.html)
        echo "::set-output name=coverage::$COVERAGE"

    - name: Comment Code Coverage and Owner Name on Pull Request
      if: github.event_name == 'pull_request'
      run: |
        owner=$(jq -r '.repository.owner.login' $GITHUB_EVENT_PATH)
        repo=$(jq -r '.repository.name' $GITHUB_EVENT_PATH)
        prNumber=$(jq -r '.number' $GITHUB_EVENT_PATH)
        coverage=$(sed -n 's/.*Overall coverage rate \([^%]*\)\%.*/\1/p' target/site/jacoco/index.html)

        if [ -n "$owner" ] && [ -n "$repo" ] && [ -n "$prNumber" ] && [ -n "$coverage" ]; then
          comment="Owner: $owner\nCode Coverage: $coverage%"
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": \"$comment\"}" \
            "https://api.github.com/repos/$owner/$repo/issues/$prNumber/comments"
        else
          echo "One or more necessary information is missing. Unable to create comment."
        fi
