name: JaCoCo Code Coverage

on:
  pull_request:
    branches:
      - master

jobs:
  jacoco:
    name: JaCoCo Coverage Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and test with JaCoCo
        run: mvn clean verify

      - name: Extract code coverage percentage
        id: coverage
        run: |
          COVERAGE=$(sed -n 's|.*<span class="ctr2">\([0-9]*\)%.*|\1|p' target/site/jacoco/index.html)
          echo "::set-output name=coverage::$COVERAGE"

      - name: Update PR description
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: console.log('Hello from GitHub Script action');
