name: Java CI with Maven

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn -B clean verify

    - name: Generate Code Coverage Report
      run: mvn -B jacoco:report

    - name: Extract Code Coverage Information
      id: coverage
      run: |
        COVERAGE=$(sed -n 's/.*Overall coverage rate \([^%]*\)\%.*/\1/p' target/site/jacoco/index.html)
        echo "::set-output name=coverage::$COVERAGE"

    - name: Comment Code Coverage on Pull Request
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const coverage = '${{ steps.coverage.outputs.coverage }}';
          const owner = context.payload.repository.owner.login;
          const repo = context.payload.repository.name;
          const prNumber = context.payload.pull_request.number;
          const comment = `Code Coverage: ${coverage}%`;
          github.issues.createComment({
            owner,
            repo,
            issue_number: prNumber,
            body: comment
          });
