name: PR Decoration with JaCoCo Coverage

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pr-decoration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Ensure execute permissions for mvnw
        run: chmod +x mvnw

      - name: Build and Test with JaCoCo
        run: |
          ./mvnw clean verify
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: ${{ github.workspace }}/target/site/jacoco/jacoco.xml

      - name: Extract Coverage Percentage
        id: extract-coverage
        run: |
          COVERAGE=$(sed -n 's/.*<span class="ctr[^>]*>\([^<]*\)<\/span>%.*$/\1/p' target/site/jacoco/index.html)
          echo "Coverage: $COVERAGE%"
          echo "::set-output name=coverage::$COVERAGE"

      - name: Post PR Comment
        if: always()
        run: |
          const coverage = "${{ steps.extract-coverage.outputs.coverage }}";
          const prNumber = github.context.payload.pull_request.number;

          // Use github.context directly
          const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

          octokit.issues.createComment({
            owner: github.context.repo.owner,
            repo: github.context.repo.repo,
            issue_number: prNumber,
            body: `Code coverage: ${coverage}%`,
          });
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
